---
# Per environment values which override defaults in hmpps-template-kotlin/values.yaml

generic-service:
  ingress:
    host: template-kotlin.hmpps.service.justice.gov.uk
    # modsecurity_enabled: true

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
 
  allowlist:
    # Configure groups as appropriate to give the minimum ingress access required:
    #   global_protect: devices using the global_protect proxy
    #   moj_cloud_platform: services on Cloud Platform
    # Other IP allowlist groups are here: 
    # https://github.com/ministryofjustice/hmpps-ip-allowlists/blob/main/ip-allowlist-groups.yaml

    groups:
      - global_protect
      - moj_cloud_platform

  # NOTE: Removing ALL allowlist groups will make the application accessible from the internet. 
  #       If you are intending to do this, please ensure you uncomment the 'modsecurity_enabled=true' 
  #       entry in the ingress above. This will enable WAF protection of the endpoint. You will need 
  #       to configure modsecurity rules to suit your needs. Further information can be found here:
  #       https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html#modsecurity-web-application-firewall



# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: PROD_ALERTS_SEVERITY_LABEL
