name: Run gradle checks
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '21'
      java-options:
        type: string
        default: ''
        required: false
      gradle-command:
        type: string
        default: './gradlew check'
        required: false
      artifact-name:
        type: string
        default: 'test-results'
        required: false
      build-dir:
        type: string
        default: 'build'
        required: false
permissions:
  contents: read
jobs:
  gradle-verify:
    name: Verify the gradle app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run checks with gradle
        shell: bash
        run: |
          export JAVA_OPTS="${{ inputs.java-options }}"
          ${{ inputs.gradle-command }}
      - name: Upload the artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            ${{ inputs.build-dir }}/test-results
            ${{ inputs.build-dir }}/reports/tests
      - name: publish test report
        if: ${{ !cancelled() }}
        uses: dorny/test-reporter@v2
        with:
          artifact: ${{ inputs.artifact-name }}
          name: Test Report
          path: 'test-results/**/*.xml'
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false
          list-suites: 'failed'
          list-tests: 'failed'
